ThreeDify Mainpage
ThreeDify/ThreeDify-web-app pull request #14
Opened 2020-10-18 17:46 UTC by SG-coder

2020-10-19 06:11 UTC, silwalanish requested changes

2020-10-19 06:11 UTC, silwalanish commented on src/Pages/MainPage.jsx
> +import Icon from '../components/Icon.jsx';
Paths are case-sensitive. 
```suggestion
import Icon from '../Components/Icon';
```

2020-10-19 06:11 UTC, silwalanish commented on src/Pages/Home.jsx
> +import MainPage from './MainPage.jsx';
Also move this import to line no 5.
```suggestion
import MainPage from './MainPage';
```

2020-10-19 06:11 UTC, silwalanish commented on src/iconSettings.js
>  const ICONS = {
Add a new line
```suggestion

const ICONS = {
```

2020-10-19 06:12 UTC, silwalanish commented on src/Pages/MainPage.jsx
> +import Icon from '../components/Icon.jsx';
This should also fix the warning in windows.

2020-10-19 06:14 UTC, silwalanish commented on src/Pages/MainPage.jsx
> +import React from 'react';
We don't need this as separate page. Move the content to `Home.jsx`

2020-10-21 12:48 UTC, silwalanish commented on src/Pages/Home.jsx
>          )}
Remove contents from line number 18 - 21.

2020-10-29 17:25 UTC, silwalanish approved these changes

2020-10-29 17:32 UTC, danny237 approved these changes

2020-10-29 17:43 UTC, silwalanish approved these changes

2020-10-29 17:43 UTC, merged