integrate API in reconstruction page
ThreeDify/ThreeDify-web-app pull request #20
Opened 2020-11-03 07:37 UTC by danny237

Error:
![image](https://user-images.githubusercontent.com/58462999/97959446-8155f380-1dd7-11eb-8666-ba3ee87a844c.png)

2020-11-03 12:47 UTC, silwalanish requested changes

2020-11-03 12:47 UTC, silwalanish commented on src/Pages/Reconstruction.jsx
> +import axios from 'axios';
Use the following [util](https://github.com/ThreeDify/ThreeDify-web-app/blob/a7d389f271c24c1062cf81b4e4af3a1325e10e13/src/Utils/axios.js#L11) instead of using out of the box `axios`.
https://github.com/ThreeDify/ThreeDify-web-app/blob/a7d389f271c24c1062cf81b4e4af3a1325e10e13/src/Utils/axios.js#L11

This handles the authorization token and refreshes them if necessary.

2020-11-03 12:47 UTC, silwalanish commented on src/Pages/Reconstruction.jsx
> +      'https://threedify-api-staging.herokuapp.com/reconstructions/create';
Store this in constants file.
https://github.com/ThreeDify/ThreeDify-web-app/blob/a7d389f271c24c1062cf81b4e4af3a1325e10e13/src/Constants/apiUrls.js#L1-L14

2020-11-03 12:47 UTC, silwalanish commented on src/Pages/Reconstruction.jsx
>      const myData = document.getElementById('form');
Use react ref instead. https://reactjs.org/docs/refs-and-the-dom.html

2020-11-03 12:47 UTC, silwalanish commented on src/Pages/Reconstruction.jsx
> +      .post(url, myData)
The data here need to be a `FormData` object not the `HTMLFormElement`.
```suggestion
      .post(url, new FormData(myData))
```

2020-11-03 12:47 UTC, silwalanish commented on src/Pages/Reconstruction.jsx
>              <button type='submit' className='btn btn-primary my-2'>
Disable the button and the inputs when the form is submited.

2020-11-03 12:47 UTC, silwalanish commented on src/Pages/Reconstruction.jsx
> +          {this.state.loading && <span>Loading...</span>}
Uploading makes more sense here. Also rename the variable accordingly.

2020-11-04 07:37 UTC, danny237 commented on src/Pages/Reconstruction.jsx
> +import axios from 'axios';
Anish, I need help. How to use this function in reconstruction page?

2020-11-05 13:23 UTC, silwalanish commented on src/Pages/Reconstruction.jsx
> +    }
:man_shrugging:

2020-11-05 13:23 UTC, silwalanish commented on src/Pages/Reconstruction.jsx
> +              (this.state.uploading || this.state.uploadSuccess) && 'd-none'
Else if the condition evaluates to false, we will have `false` as class in the form element.
```suggestion
              (this.state.uploading || this.state.uploadSuccess) ? 'd-none' : ''
```

2020-11-05 13:23 UTC, silwalanish commented on src/Pages/Reconstruction.jsx
> +              {' '}
:shrug:

2020-11-05 13:23 UTC, silwalanish commented on src/Pages/Reconstruction.jsx
> +              {' '}
:shrug:

2020-11-05 13:23 UTC, silwalanish commented on src/Pages/Reconstruction.jsx
> +                <Link to={RECONSTRUCTION_URL}>Reconstruct Again</Link>
I don't think we need to redirect the user.
```suggestion
                Reconstruct Again
```

2020-11-05 13:23 UTC, silwalanish commented on src/Pages/Reconstruction.jsx
> +                <Link to={RECONSTRUCTION_URL}>Try Again</Link>
```suggestion
                Try Again
```

2020-11-05 13:23 UTC, silwalanish commented on src/Pages/Reconstruction.jsx
> +    this.form.current.reset();
We might need to check if current is a valid object.
```suggestion
    this.form.current && this.form.current.reset();
```

2020-11-05 13:59 UTC, silwalanish commented
@danny237 Looks good.

2020-11-05 14:00 UTC, silwalanish approved these changes

2020-11-05 14:01 UTC, SG-coder approved these changes

2020-11-05 14:01 UTC, KGhising approved these changes

2020-11-05 14:01 UTC, merged