Show the top 9 most recent reconstruction in explore page
ThreeDify/ThreeDify-web-app pull request #23
Opened 2020-11-08 15:46 UTC by KGhising

- show the top 9 most recent reconstruction in explore page
- card style change on ReconstructionsCard

2020-11-08 16:11 UTC, silwalanish requested changes

2020-11-08 16:11 UTC, silwalanish commented on src/Components/ReconstructionCard.jsx
> +                Created by{' '}
???

2020-11-08 16:11 UTC, silwalanish commented on src/Components/ReconstructionCard.jsx
> +                Created by{' '}
Where is showCreator logic????

2020-11-08 16:11 UTC, silwalanish commented on src/Pages/Explore.jsx
> +    );
Not needed.

2020-11-08 16:11 UTC, silwalanish commented on src/Pages/Explore.jsx
> +  async reconstructionCardFetchHandler() {
rename to fetchReconstructions

2020-11-08 16:15 UTC, KGhising commented on src/Components/ReconstructionCard.jsx
> +                Created by{' '}
I think showCreator is not necessary. Does Construction without username exist?

2020-11-08 16:16 UTC, KGhising commented on src/Pages/Explore.jsx
> +    );
Okay

2020-11-08 16:16 UTC, KGhising commented on src/Pages/Explore.jsx
> +  async reconstructionCardFetchHandler() {
Okay

2020-11-08 18:19 UTC, SG-coder approved these changes

2020-11-08 18:23 UTC, SG-coder approved these changes

2020-11-09 06:29 UTC, silwalanish commented on src/Pages/Explore.jsx
> +
???

2020-11-09 09:46 UTC, silwalanish approved these changes

2020-11-09 09:46 UTC, silwalanish commented on src/Components/ReconstructionCard.jsx
> +                className={this.props.showCreator ? '' : 'heading-showCreator'}
Name class appropriately.
```suggestion
                className={!this.props.showCreator ? 'heading-creator-hidden' : ''}
```

2020-11-09 13:16 UTC, silwalanish approved these changes

2020-11-09 13:17 UTC, merged