adding pagination and implement tabs
ThreeDify/ThreeDify-web-app pull request #38
Opened 2020-11-30 14:38 UTC by danny237

2020-11-30 19:02 UTC, silwalanish requested changes

2020-12-01 02:06 UTC, danny237 commented on package.json
> +    "@material-ui/lab": "^4.0.0-alpha.56",
Ok!

2020-12-01 15:10 UTC, silwalanish commented on src/Pages/Reconstruction.jsx
> +    ));
Do this with one loop.

2020-12-01 15:28 UTC, danny237 commented on src/Pages/Reconstruction.jsx
> +    ));
I have tried that but error aayo!

2020-12-02 13:34 UTC, silwalanish approved these changes

2020-12-02 13:37 UTC, merged